# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLASSGRPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('classgroupid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CLASSGRPS',
            },
        ),
    ]
