# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170626_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classgrps',
            table='"CMIS_OWNER"."CLASSGRPS"',
        ),
    ]
