# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170626_1508'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classgrps',
            table='CLASSGRPS',
        ),
    ]
