# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170626_1517'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classgrps',
            table='CMIS_OWNER.CLASSGRPS',
        ),
    ]
