# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20170627_1441'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classgrps',
            table='"CMIS_OWNER"."CLASSGRPS"',
        ),
    ]
