# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20170627_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotid', models.IntegerField()),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('classgroupid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'TIMETABLE',
                'managed': False,
            },
        ),
    ]
